- hosts: 
    - server
  become: true
  tasks:
    - name: Get PM2 startup command
      become: true
      command: pm2 startup 
      changed_when: false
      register: pm2_startup_cmd

    - debug:
        var: pm2_startup_cmd.stdout_lines
    
    - name: run startup
      become: true
      shell: sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu

    - name: save startup
      become: true
      shell: pm2 save
